# /*******************************************************************************
#  * Copyright 2021 Intel Corporation.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  *******************************************************************************/

version: '3.7'

services:
  app-service-functional-tests:
    image: ${APP_SVC_REPOSITORY}/app-service-configurable${ARCH}:${APP_SERVICE_CONFIG_VERSION}
    ports:
      - 59705:59705/tcp
    container_name: app-functional-tests
    hostname: app-functional-tests
    env_file:
      - common.env
      - as-common.env
    environment:
      EDGEX_PROFILE: functional-tests
      SERVICE_HOST: app-functional-tests
    depends_on:
      - consul
      - data
    read_only: true
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
    user: "${EDGEX_USER}:${EDGEX_GROUP}"

  scalability-test-mqtt-export:
    image: ${APP_SVC_REPOSITORY}/app-service-configurable${ARCH}:${APP_SERVICE_CONFIG_VERSION}
    ports:
      - "59710:59703" #Exposing as different port to avoid conflict with other MQTT export instance
    container_name: edgex-scalability-test-mqtt-export
    hostname: edgex-scalability-test-mqtt-export
    env_file:
      - common.env
      - as-common.env
      - asc-mqtt-export.env
    environment:
      EDGEX_SERVICE_KEY: app-scalability-test-mqtt-export
      SERVICE_HOST: edgex-scalability-test-mqtt-export
      WRITABLE_PIPELINE_FUNCTIONS_MQTTEXPORT_PARAMETERS_CLIENTID: scalability-test-mqtt-export
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_CLIENTID: app-scalability-test-mqtt-export
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    read_only: true
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
    user: "${EDGEX_USER}:${EDGEX_GROUP}"
